server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://116.196.102.44:3306/sdk?characterEncoding=UTF-8
    username: root
    password: mysql@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect